FOGL-7566 Terminate poll wait early if a reconfiguration reduces the poll
fledge-iot/fledge pull request #1030
Opened 2023-03-30 10:32 UTC by MarkRiddoch

wait time

2023-03-30 15:58 UTC, pintomax requested changes

2023-03-30 15:58 UTC, pintomax commented on C/services/south/south.cpp
> +		else
better to use
{
     return;
}

2023-03-31 10:10 UTC, AmandeepArora approved these changes

2023-03-31 10:19 UTC, pintomax approved these changes

2023-03-31 14:34 UTC, merged