FOGL-7980 Initial perforamnce coutner implemetation
fledge-iot/fledge pull request #1123
Opened 2023-07-24 14:28 UTC by MarkRiddoch

2023-07-25 20:57 UTC, RVerhoeff commented on C/services/south/ingest.cpp
> +	m_performance->collect("queueLegnth", (long)queueLength());
Typo

2023-07-25 20:57 UTC, RVerhoeff commented on C/services/south/ingest.cpp
> +	m_performance->collect("queueLegnth", (long)queueLength());
Typo

2023-07-25 20:57 UTC, RVerhoeff commented on C/services/south/ingest.cpp
> + * We do this in a seperate function so that we can lock the qMutex
Typo: separate

2023-07-25 21:05 UTC, RVerhoeff requested changes
Typos

2023-07-26 07:09 UTC, pintomax submitted a review, later dismissed

2023-07-26 13:35 UTC, MarkRiddoch commented
> Typos

It's funny how you read what you think you have written!

2023-07-26 13:57 UTC, RVerhoeff approved these changes

2023-07-26 14:39 UTC, merged