FOGL-7839: Improvements in valgrind test to check memory leakage
fledge-iot/fledge pull request #1131
Opened 2023-08-04 08:06 UTC by Mohit04tomar

2023-08-14 13:33 UTC, ashish-jabble requested changes

2023-08-14 13:33 UTC, ashish-jabble commented on tests/system/memory_leak/scripts/setup
> +	sudo sed -i '/.\/fledge.services.south.*/s/^/valgrind --xml=yes --xml-file=\/tmp\/north_valgrind_%p.xml --track-origins=yes '"$valgrind_conf"' /' ${psouth_c}
it should be with **north** Not south

2023-08-14 13:33 UTC, ashish-jabble commented on tests/system/memory_leak/scripts/setup
> +	sudo sed -i '/.\/fledge.services.south.*/s/^/valgrind --xml=yes --xml-file=\/tmp\/storage_valgrind_%p.xml --track-origins=yes '"$valgrind_conf"' /' ${psouth_c}
it should be with **storage** Not south

2023-08-14 13:33 UTC, ashish-jabble commented on tests/system/memory_leak/test_memcheck.sh
> +COLLECT_FILES="$2"
It should have some default value; And if pass then accept that. Also we may add validation to accept possible values like  XML, LOGS

2023-08-14 13:33 UTC, ashish-jabble commented on tests/system/memory_leak/test_memcheck.sh
> +  fi
More simpler way
```
extension="xml"
if [[ "${COLLECT_FILES}" == "LOGS" ]]; then extension="log"; fi
cp -rf /tmp/*valgrind*.${extension} reports/test1/. && echo 'copied'
```

2023-08-14 13:33 UTC, ashish-jabble commented on tests/system/memory_leak/test_memcheck.sh
>    mkdir -p reports/test1 ; ls -lrth
Not sure why are we creating reports directory with **test1**? What does it really mean?

2023-08-23 06:58 UTC, ashish-jabble commented on tests/system/memory_leak/scripts/setup
> +COLLECT_FILES=${3}
Always better argument in double quotes "$3"

2023-08-23 07:00 UTC, ashish-jabble approved these changes
Not sure If [FOGL-7839](https://github.com/fledge-iot/fledge/compare/FOGL-7839) branch is required as Mark has committed some of the commits onto same branch and rebased with this.
Either we need to change its base branch to FOGL-7839 or get it first merged into develop and then Rebase FOGL-7839 branch with develop

2023-08-29 19:31 UTC, praveen-garg approved these changes

2023-08-30 12:27 UTC, merged