Updated 91_version_history file for 2.3.0 release
fledge-iot/fledge pull request #1260
Opened 2024-01-05 13:08 UTC by Mohit04tomar

2024-01-05 13:32 UTC, praveen-garg commented on docs/91_version_history.rst
> +       - A memory leak in the SQLite In Memory storage plugin has been resolved.
SQLite in-memory


Be consistent with naming such, For better search.

2024-01-05 13:32 UTC, praveen-garg commented on docs/91_version_history.rst
> +       - An issue that meant some OPCUA nodes stored in the root of the hierarchy were not correctly ingested in the S2OPCUA south plugin has been resolved.
We should be consistent with `OPC UA` (see space) or OPC/UA.

Also for `S2OPCUA south plugin`, The occurrences of fldege-south-s2opcua should be replaced as we have here.

2024-01-05 13:32 UTC, praveen-garg commented on docs/91_version_history.rst
> +       - The S2 OPCUA south plugin has been enhanced to allow filtering of nodes using regular expressions on the name of the nodes.
S2OPCUA

2024-01-05 13:32 UTC, praveen-garg commented on docs/91_version_history.rst
> +       - An issue with using an OMF Hint that defines a specific name to us with a tag has been resolved. The issue would show itself as the data not being sent to PI or ADH in some circumstances.
We should put these on top in bug fixes, including memory leak fix.

2024-01-05 19:10 UTC, RVerhoeff commented on docs/91_version_history.rst
> +       - The user interface for creating write API endpoints was incorrectly requiring both a constant and a variable when only one is required, this is now resolved.
New sentence: "...one is required. This is now resolved."

2024-01-05 19:12 UTC, RVerhoeff commented on docs/91_version_history.rst
> +       - The S2 OPCUA south plugin has been enhanced to allow filtering of nodes using regular expressions on the name of the nodes.
It's "...on the Browse Name of the nodes." This is OPC UA terminology which is important in this case.

2024-01-05 19:13 UTC, RVerhoeff commented on docs/91_version_history.rst
> +       - The SQLite storage plugin had an issue that caused it to create overflow tables multiple times. This was not a problem in itself, but did cause the database to become looked for excessive pe
I believe "_looked_" should be "_locked._"

2024-01-05 19:16 UTC, RVerhoeff commented on docs/91_version_history.rst
> +       - An issue with using an OMF Hint that defines a specific name to us with a tag has been resolved. The issue would show itself as the data not being sent to PI or ADH in some circumstances.
Typo: _specific name to us_ -> _specific name to use_

2024-01-05 19:18 UTC, RVerhoeff requested changes
A few typos.

2024-01-08 10:49 UTC, MarkRiddoch approved these changes

2024-01-08 13:52 UTC, RVerhoeff approved these changes

2024-01-09 08:31 UTC, merged