FOGL8738: Improve north statistics
fledge-iot/fledge pull request #1362
Opened 2024-05-20 08:51 UTC by pintomax

FOGL8738: Improve north statistics

2024-05-20 08:56 UTC, pintomax commented
Example contend of database table statistics

sqlite> select * from statistics;
R1-Ingest|Readings received from service R1|525|487|2024-05-20 10:47:48.713
RANDOM|Readings received from asset Random|525|487|2024-05-20 10:47:52.488
HT1|HT1 Readings Sent|487|450|2024-05-20 10:47:55.878
Readings Sent|Readings Sent Noth|974|900|2024-05-20 10:47:55.880
HT2|HT2 Readings Sent|487|450|2024-05-20 10:47:55.886

2024-05-20 10:26 UTC, MarkRiddoch requested changes

2024-05-20 10:26 UTC, MarkRiddoch commented on C/services/north/data_send.cpp
> +	if (m_shutdown)
It should still flush the statistics if shutdown has been set

2024-05-20 10:26 UTC, MarkRiddoch commented on C/services/north/data_send.cpp
> +		m_loader->updateStatistic(it->first, description, it->second);
No, this is wrong, you are still making multiple calls to the storage layer. The idea is to make one call to the storage layer with all the statistics to update.

2024-05-21 13:22 UTC, MarkRiddoch approved these changes

2024-05-21 14:48 UTC, MarkRiddoch approved these changes

2024-05-21 14:49 UTC, merged