FOGL-8982 Add documentation on allow and deny lists
fledge-iot/fledge pull request #1439
Opened 2024-08-06 11:37 UTC by MarkRiddoch

2024-08-06 13:18 UTC, ashish-jabble requested changes
Checkin only with screenshot?
Add some details for the firewall in secure fledge page.

Also, this screenshot needs to be updated once GUI issue FOGL-8978 is resolved. 
Like Display name and description is Not appearing for list type on configuration page.

2024-08-07 08:46 UTC, MarkRiddoch commented
> Checkin only with screenshot? Add some details for the firewall in secure fledge page.
> 
> Also, this screenshot needs to be updated once GUI issue FOGL-8978 is resolved. Like Display name and description is Not appearing for list type on configuration page.

Whoops, sorry, forgot to add the other file to the commit.

2024-08-08 07:43 UTC, ashish-jabble commented on docs/securing_fledge.rst
> +If the allow list is non-empty, then any access, including ping, to the Fledge API port will be checked to see if the source IP address of the request matches an entry in the allow list. If the addre
space required - `andthe`

2024-08-08 08:03 UTC, ashish-jabble commented on docs/securing_fledge.rst
> +Allow & Block Lists
Block -> Deny (Consistency wise)

2024-08-08 08:04 UTC, ashish-jabble commented on docs/securing_fledge.rst
> +To remove an entry from the list click on the *x* icon to the right of the list item.
It will be better if we add numbered bullet points for each

2024-08-08 08:05 UTC, ashish-jabble commented
@MarkRiddoch Would you mind to replace the screenshot with below? This is created from GUI branch FOGL-8978, as display name, description, order handling is missing in develop for the list type config items on Configuration page.

![firewall](https://github.com/user-attachments/assets/b90381a9-43aa-4303-ad05-31db50539bce)

2024-08-08 13:09 UTC, merged