fledge specific documentation updates for v2.6.0
fledge-iot/fledge pull request #1479
Opened 2024-10-25 07:52 UTC by ashish-jabble

2024-10-25 08:20 UTC, MarkRiddoch approved these changes

2024-10-25 12:51 UTC, ashish-jabble commented on docs/91_version_history.rst
>         - An issue with the user interface incorrectly displaying a timestamp has been resolved.
throughout where we display time

2024-10-25 13:05 UTC, ashish-jabble commented on docs/91_version_history.rst
> +       - fledge-south-s2opcua now supports for the OPC UA Data Change Filter has been added. This filter type is defined in the `OPC UA Specification, Part 4, Section 7.22.2 <https://reference.opcfou
See https://reference.opcfoundation.org/Core/Part4/v105/docs/7.22.2

2024-10-27 02:23 UTC, RVerhoeff commented on docs/91_version_history.rst
> +       - Failures to send data north via the north service raise an alert, this is now cleared if the flow of data north later resumes.
Start a new sentence at "This is now cleared if..."

2024-10-27 02:24 UTC, RVerhoeff requested changes
One minor sentence fix. I am on vacation this week so please ask one of the other reviewers to finish this.

2024-10-27 13:30 UTC, praveen-garg commented on docs/91_version_history.rst
> +       - fledge-south-s2opcua now supports for the OPC UA Data Change Filter has been added. This filter type is defined in the `OPC UA Specification, Part 4, Section 7.22.2 <https://reference.opcfou
I mean it should be 

now supports


The words "has been added" should be removed.

2024-10-27 17:18 UTC, praveen-garg commented on docs/91_version_history.rst
>         - An issue with the user interface incorrectly displaying a timestamp has been resolved.
I think in both cases, the API and UI, it was fixed on Backup & Restore only.

2024-10-27 17:29 UTC, praveen-garg commented on docs/91_version_history.rst
> +       - fledge-north-OMF *action* code in the HTTP header is normally set to *update* for OMF Data messages. This causes old values to be updated if the timestamps match and new data to be properly
The OMF north plugin's *action* code in the HTTP header is typically set to *update* for OMF Data messages. This setting allows old values to be updated when timestamps match and ensures that new data is compressed correctly by the PI Data Archive. However, if the AVEVA PI Buffer Subsystem is configured, the *update* action code is converted to an internal PI storage mode, which causes new data to bypass compression and may lead to excessive storage of too many data values. To address this issue, the OMF North plugin now allows you to change the OMF Data action code to *create*. This option should only be used when the AVEVA PI Buffer Subsystem is configured.

2024-10-28 06:04 UTC, merged