Updated reset_and_start fixture
fledge-iot/fledge pull request #1524
Opened 2024-12-24 06:56 UTC by Mohit04tomar

2024-12-24 08:10 UTC, ashish-jabble requested changes

2024-12-24 08:10 UTC, ashish-jabble commented on tests/system/python/conftest.py
> +        shell=True, check=True)
Considering the spaces in readings value
```
["echo", "$(jq -c --arg READINGS_PLUGIN_VAL '{}'.format(readings_plugin), '.readingPlugin.value=$READINGS_PLUGIN_VAL' $FLEDGE_ROOT/data/etc/storage.json) > $FLEDGE_ROOT/data/etc/storage.json"], shell=True, check=True)
```

2024-12-24 13:56 UTC, ashish-jabble approved these changes

2024-12-26 07:14 UTC, Mohit04tomar commented
Following test run on changes of latest commit(13afcde) this pull request:
http://jenkins.dianomic.com:8080/job/fledge_on_demand_code_coverage_ub2004/133/

2024-12-26 07:14 UTC, merged