FOGL-4823 Do not add asset tracker records when send fails
fledge-iot/fledge pull request #234
Opened 2020-12-18 11:41 UTC by MarkRiddoch

Signed-off-by: Mark Riddoch <mark@dianomic.com>

2020-12-18 11:55 UTC, pintomax approved these changes

2020-12-21 12:49 UTC, ashish-jabble requested changes
@MarkRiddoch It still have an issue.
```
1) curl -sX GET http://localhost:8081/fledge/service
    {
      "name": "NS-1",
      "type": "Northbound",
      "address": "localhost",
      "management_port": 35279,
      "service_port": null,
      "protocol": "http",
      "status": "running"
    },
    {
      "name": "RW",
      "type": "Southbound",
      "address": "localhost",
      "management_port": 33391,
      "service_port": null,
      "protocol": "http",
      "status": "running"
    }

2. curl -sX GET http://localhost:8081/fledge/ping

{
  "uptime": 441,
  "dataRead": 157,
  "dataSent": 0,
  "dataPurged": 0,
  "authenticationOptional": true,
  "serviceName": "Fledge",
  "hostName": "aj-ub1804",
  "ipAddresses": [
    "192.168.1.8"
  ],
  "health": "green",
  "safeMode": false
}

3. curl -sX GET http://localhost:8081/fledge/track

{
  "track": [
    {
      "asset": "randomwalk",
      "event": "Ingest",
      "service": "RW",
      "fledge": "Fledge",
      "plugin": "randomwalk",
      "timestamp": "2020-12-21 18:09:29.954"
    },
    {
      "asset": "randomwalk",
      "event": "Egress",
      "service": "NS-1",
      "fledge": "Fledge",
      "plugin": "httpc",
      "timestamp": "2020-12-21 18:09:33.290"
    }
  ]
}
```
Egress entry still there with "dataSent": 0

2021-01-04 14:57 UTC, pintomax approved these changes

2021-01-05 07:49 UTC, ashish-jabble approved these changes
Now looks good.

2021-01-05 15:22 UTC, merged