FOGL-6160: Sqlite plugin documentation, multiple readings handling
fledge-iot/fledge pull request #553
Opened 2022-01-26 08:29 UTC by sstefano69

Signed-off-by: Stefano <stefano@dianomic.com>

2022-01-28 08:25 UTC, pintomax requested changes

2022-01-28 08:25 UTC, pintomax commented on C/plugins/storage/sqlite/common/readings_catalogue.cpp
> + * @param newDbId      If of the created database to create
This is not clear

2022-01-28 09:51 UTC, MarkRiddoch submitted a review, later dismissed

2022-01-28 11:21 UTC, sstefano69 commented on C/plugins/storage/sqlite/common/readings_catalogue.cpp
> + * @param newDbId      If of the created database to create
yes, it is a typo: If -> Id

2022-01-31 09:32 UTC, pintomax approved these changes

2022-01-31 14:34 UTC, merged