FOGL-6100: call a callback when a child category is created/deleted
fledge-iot/fledge pull request #596
Opened 2022-03-10 16:03 UTC by pintomax

FOGL-6100: call a callback when a child category is created/deleted

2022-03-11 09:31 UTC, MarkRiddoch requested changes
Looks good, just a few minor things

2022-03-11 09:31 UTC, MarkRiddoch commented on C/common/management_client.cpp
> + * Register interest in a configuration category
Please add @param and @return items

2022-03-11 09:31 UTC, MarkRiddoch commented on C/common/management_client.cpp
> +			m_logger->error("Failed to register configuration category: %s.",
It might be worth adding "child" to the message so we can distinguish it from the routine below.

2022-03-11 09:31 UTC, MarkRiddoch commented on C/common/management_client.cpp
> +                m_logger->error("Register configuration category failed %s.", e.what());
Likewise adding "child" would help debugging issues

2022-03-11 09:31 UTC, MarkRiddoch commented on C/services/common/config_handler.cpp
> +			m_logger->error("Failed to register configuration category %s", category.c_str());
Adding child would help in debugging

2022-03-14 11:37 UTC, MarkRiddoch reviewed
Looks good so far. Just need the order thing we talked about

2022-03-14 18:09 UTC, praveen-garg commented on python/fledge/services/core/server.py
> +                value = data.get('child', None)
keep default false?
Also keep first line as
``` 
child_subscribe = False 
if value/isChildren not an instance of bool:
   return error or pass (as already assigned a false)
else 
  child_subscribe = isChildren
```

2022-03-14 18:09 UTC, praveen-garg commented on python/fledge/services/core/server.py
> +
avoid extra newlines

2022-03-14 18:09 UTC, praveen-garg commented on tests/unit/python/fledge/services/core/api/test_notification.py
>      @pytest.mark.parametrize("notification_instance_name, channel_name, message", [
I'm not clear on changes of this test

2022-03-14 18:09 UTC, praveen-garg commented on tests/unit/python/fledge/services/core/api/test_notification.py
>      ])
Needs explanation around test data and how mocking are expected to be that way.

2022-03-14 18:38 UTC, pintomax commented on python/fledge/services/core/api/notification.py
> +        the first having the naming : delivery +  "NotificationName"
@praveen-garg this naming convention is for the extra delivery only

The Notification created via existing API adds: for notification name A these 3 categories
A, ruleA and deliveryA

So we always have a delivery channel.

Assuming we want to add a new one: telegramDelivery a new category is created
A_channel_telegramDelivery

This is consistent with any new extra delivery we will add later.

This approach also works fine with FogLAMP Manage which can deal as per current work in progress with
add, update and delete of extra channels and deployment.

When testing, very soon, the onboarding of instance I'll will be clear whether we might change this naming convention or not.

2022-03-15 08:48 UTC, praveen-garg reviewed
sqlitelb up/down scripts missing?

Adding an instance with inbuilt rule and asset delivery causing crash; and notification service goes unresponsive.

2022-03-15 08:48 UTC, praveen-garg commented on scripts/plugins/storage/sqlitelb/init.sql
> +CREATE TABLE category_children (
Add fledge.?

2022-03-15 09:08 UTC, pintomax commented
> sqlitelb up/down scripts missing?
> 
> Adding an instance with inbuilt rule and asset delivery causing crash; and notification service goes unresponsive.

Did you test with fledge-service-notification branch FOGL-6056 ?

2022-03-15 09:20 UTC, praveen-garg commented
> > sqlitelb up/down scripts missing?
> 
> > 
> 
> > Adding an instance with inbuilt rule and asset delivery causing crash; and notification service goes unresponsive.
> 
> 
> 
> Did you test with fledge-service-notification branch FOGL-6056 ?

No

Let's try with that! 

If single delivery channel is used, develop branch based GUI is okay to use; and there is no such REST interface changed Or you suggest specific cURL commands?

2022-03-15 09:23 UTC, praveen-garg commented
This pull request requires https://github.com/fledge-iot/fledge-service-notification/pull/41

2022-03-15 10:45 UTC, pintomax commented
> > > Adding an instance with inbuilt rule and asset delivery causing crash; and notification service goes unresponsive.
> > 
> > 
> > Did you test with fledge-service-notification branch FOGL-6056 ?
> 
> No
> 
> Let's try with that!
> 
> If single delivery channel is used, develop branch based GUI is okay to use; and there is no such REST interface changed Or you suggest specific cURL commands?

2022-03-15 10:48 UTC, pintomax commented
> > > Adding an instance with inbuilt rule and asset delivery causing crash; and notification service goes unresponsive.
> > 
> > 
> > Did you test with fledge-service-notification branch FOGL-6056 ?
> 
> No
> 
> Let's try with that!
> 
> If single delivery channel is used, develop branch based GUI is okay to use; and there is no such REST interface changed Or you suggest specific cURL commands?

My setup
- Fledge branch FOGL-6100
- Notification server branch develop (compiled with FLEDGE_ROOT=FOGL-6100
- "asset" delivery plugin branch develop (compiled with FLEDGE_ROOT=FOGL-6100 and NOTIFICATION_SERVICE_INCLUDE_DIRS=$fledge-notification-develop_inludes

I can add a Notification instance and I see notifications, no crashes.

Also tested "Telegram" and "Blink" plugins from develop, recompiled as above

2022-03-15 13:06 UTC, pintomax commented
Note: if using "develop" of fledge-service-notification, then 

configChildCreate and configChildDelete empty routines must be added in C/services/common/include/notification_service.h in order to compile the service

2022-03-15 13:31 UTC, praveen-garg commented on C/services/common/include/management_api.h
> +#define CONFIG_CHILD_DELETE "/fledge/child_delete"
is there any architectural doc explaining these new endpoints for micro-services to have?  I really wonder if change endpoint cannot be used and we really need 2 explicit endpoints for child category create & delete.

2022-03-16 11:40 UTC, MarkRiddoch submitted a review, later dismissed

2022-03-22 17:41 UTC, MarkRiddoch submitted a review, later dismissed

2022-05-30 09:07 UTC, MarkRiddoch approved these changes

2022-06-13 07:34 UTC, merged