FOGL-6286 ACL field optional on UPDATE script
fledge-iot/fledge pull request #597
Opened 2022-03-15 12:18 UTC by ashish-jabble

Signed-off-by: ashish-jabble <ashish@dianomic.com>

2022-03-15 13:48 UTC, mshariq-nerd requested changes
Not able to attach already created or empty ACL with the script. Throwing error `ACL with name is not found`
```
curl -H "authorization: $AUTH_TOKEN" -sX PUT http://localhost:8081/fledge/control/script/testScript -d '{"steps": [{"delay": {"order": 1, "duration": 12}}], "acl": "testACL"}' | jq
{
  "message": "ACL with name testACL is not found."
}

 curl -H "authorization: $AUTH_TOKEN" -sX PUT http://localhost:8081/fledge/control/script/testScript -d '{"steps": [{"delay": {"order": 1, "duration": 12}}], "acl": ""}' | jq
{
  "message": "ACL with name  is not found."
}

```

2022-03-15 14:06 UTC, ashish-jabble commented
@mshariq-nerd First Curl response should be right, It seems to be ACL with name "testACL" prerequisite is missing in your setup. You need to first create ACL with name "testACL". Else send me the response for
```
curl -sX GET localhost:8081/fledge/ACL
```
Second Curl response is now handled with latest commit.

2022-03-15 14:31 UTC, mshariq-nerd commented
Both cURLs working fine now, able to attache ACL. However seeing couple of issues 
```
1. Add script
curl -sX POST http://localhost:8081/fledge/control/script -d '{"name":"demoScript","steps":[{"delay":{"order":1,"duration":900}}]}' | jq

2. Add ACL
curl -sX POST http://localhost:8081/fledge/ACL -d '{"name":"demoACL","service":[{"name":"Fledge Storage"},{"type":"Southbound"}],"url":[{"url":"/foglamp/south/operation","acl":[{"type":"Southbound"}]}]}'| jq

3. Attache ACL with script
 curl  -sX PUT http://localhost:8081/fledge/control/script/demoScript -d '{"steps": [{"delay": {"order": 1, "duration": 900}}], "acl": "demoACL"}' | jq
{
  "message": "Control script demoScript updated successfully."
}

4. pass empty ACL to remove old attached ACL from script. says success
 curl  -sX PUT http://localhost:8081/fledge/control/script/demoScript -d '{"steps": [{"delay": {"order": 1, "duration": 900}}], "acl": ""}' | jq
{
  "message": "Control script demoScript updated successfully."
}

5. GET script by name. See response **demoACL** still attached with the script 
curl -H -sX GET http://localhost:8081/fledge/control/script/demoScript | jq
{
  "name": "demoScript",
  "steps": [
    {
      "delay": {
        "order": 1,
        "duration": 900
      }
    }
  ],
  "acl": "demoACL"
}

6. Also if payload passed without acl key then getting error
curl -sX PUT http://localhost:8081/fledge/control/script/demoScript -d '{"steps": [{"delay": {"order": 1, "duration": 900}}]}' | jq
{
  "message": "object of type 'NoneType' has no len()"
}

```

2022-03-16 09:59 UTC, mshariq-nerd approved these changes

2022-03-16 10:26 UTC, merged