Added API definition for version 1.5.0
fledge-iot/fledge pull request #665
Opened 2022-05-31 14:38 UTC by Innovative-ashwin

Signed-off-by: Innovative-ashwin <sinha.ashwini111@gmail.com>

2022-05-31 14:40 UTC, Innovative-ashwin commented
This requires testing along with FOGL_6451 , only after testing gets completed , this can be merged to develop.
Testing requires FOGL_6451 to be completed.

2022-06-01 08:19 UTC, MarkRiddoch submitted a review, later dismissed

2022-06-06 09:51 UTC, MarkRiddoch submitted a review, later dismissed
This looks ok to me. We do need to have an update to init.sql and upgrade and downgrade scripts for all the databases (Postgres and SQLite), this woudl be for the table that tracks the schemas.

2022-06-06 10:28 UTC, Innovative-ashwin commented on C/plugins/storage/postgres/plugin.cpp
>  	"1.0.0",                  // Version
@MarkRiddoch  will this change this to 1.2.0?

2022-06-07 08:37 UTC, MarkRiddoch requested changes

2022-06-07 09:23 UTC, Innovative-ashwin commented on C/plugins/storage/postgres/connection.cpp
> +									sprintf(msg, "Function: %s, Schema:%s, Service:%s, tableName:%s, Error in executing drop index command %s",__FUNCTION__, schema.c_str(), service.c_str(), name.c_str(), sqlIdx.c_str());
Fixed

2022-06-07 09:33 UTC, Innovative-ashwin commented on C/plugins/storage/postgres/plugin.cpp
>  	"1.0.0",                  // Version
Fixed

2022-06-07 09:42 UTC, MarkRiddoch approved these changes

2022-06-07 11:11 UTC, merged