FOGL-6670 Developer Features and OMF Types in troubleshooting OMF
fledge-iot/fledge pull request #750
Opened 2022-07-25 16:22 UTC by MarkRiddoch

2022-07-27 15:19 UTC, RVerhoeff commented on docs/troubleshooting_pi-server_integration.rst
> +The OMF north plugin must create type information within the OMF subsystem of the PI server before any data can be sent. This type information is persisted within the PI Server between sessions and m
PI Server

2022-07-27 15:22 UTC, RVerhoeff commented on docs/troubleshooting_pi-server_integration.rst
> +    This is the opposite problem to that stated above, the plugin will try to send data thinking that the types have already been created in the PI Server and receive an error. Fledge will automatica
Add comma: "To re-use the previous names, stopping..."

2022-07-27 15:23 UTC, RVerhoeff commented on docs/troubleshooting_pi-server_integration.rst
> +    This new PI server will not have the type information from the old and we will once again get errors when sending data due to these missing types. Fledge will automatically correct for this and c
Space in word: "which ma y not be the desired behavior"

2022-07-27 15:24 UTC, RVerhoeff commented on docs/troubleshooting_pi-server_integration.rst
> +names stopping the north service and deleting the plugin persisted data will reset the algorithm and recreate the types using the names that had been previously used.
Add comma: "To re-use the previous names, stopping..."

2022-07-27 15:26 UTC, RVerhoeff commented on docs/troubleshooting_pi-server_integration.rst
> +Navigate to the *Settings* page of the GUI and toggle on the *Developer Features* tick box on the bottom left of the page.
_check_ box?

2022-07-27 15:28 UTC, RVerhoeff commented on docs/troubleshooting_pi-server_integration.rst
> +| afHierarchyOrig | The original setting of AF Heirarchy. This may differ from the above if specific AF rules |
Should be "Hierarchy"

2022-07-27 15:29 UTC, RVerhoeff requested changes
I commented on using "PI Server" instead of "PI server" in one place but it applies throughout.

2022-08-02 01:47 UTC, ashwinscale approved these changes
LGTM

2022-08-02 14:26 UTC, RVerhoeff approved these changes

2022-08-02 14:45 UTC, ashwinscale approved these changes
LGTM

2022-08-02 17:33 UTC, merged