FOGL 6784 - New API endpoint to install Python packages
fledge-iot/fledge pull request #794
Opened 2022-08-23 08:28 UTC by cyberwalk3r

2022-08-23 08:59 UTC, MarkRiddoch requested changes
This looks pretty good to me. The only comment is around the code that has been commented out. If it is needed then dot comment it out. If it is not needed then please remove it.

2022-08-23 08:59 UTC, MarkRiddoch commented on python/fledge/services/core/api/python_packages.py
> +    # def is_canonical(version):
In general I don't like having commented out code in the source - it makes future visitors unsure why it is there.

2022-08-23 08:59 UTC, MarkRiddoch commented on python/fledge/services/core/api/python_packages.py
> +    # if is_canonical(input_package_version) == None:
If the is a valid check then why not include it, otherwise take it out of the code.

2022-08-23 08:59 UTC, MarkRiddoch commented on python/fledge/services/core/api/python_packages.py
> +            # code = subprocess.run([sys.executable, '-m', 'pip', 'install', install_string], capture_output=True, text=True, encoding='utf-8')
Please remove

2022-08-23 12:58 UTC, MarkRiddoch approved these changes

2022-08-24 08:33 UTC, MarkRiddoch submitted a review, later dismissed

2022-08-24 13:02 UTC, MarkRiddoch submitted a review, later dismissed

2022-08-24 13:15 UTC, mshariq-nerd approved these changes

2022-08-24 13:45 UTC, MarkRiddoch approved these changes

2022-08-24 14:02 UTC, merged