FOGL-6887 API to get Storage & data directory disk health
fledge-iot/fledge pull request #825
Opened 2022-09-15 12:57 UTC by deepanshu-yadav

Request Example 

`curl -sX GET http://localhost:8081/fledge/health/storage  |jq`

Sample Response 
```
{
  "uptime": 11,
  "name": "Fledge Storage",
  "statistics": {
    "commonInsert": 28,
    "commonSimpleQuery": 2,
    "commonQuery": 91,
    "commonUpdate": 0,
    "commonDelete": 1,
    "readingAppend": 0,
    "readingFetch": 0,
    "readingQuery": 1,
    "readingPurge": 0
  },
  "disk": {
    "used": 94831296,
    "usage": 82,
    "available": 21374336,
    "status": "green"
  }
}

```

2022-09-15 16:15 UTC, MarkRiddoch requested changes

2022-09-15 16:15 UTC, MarkRiddoch commented on python/fledge/services/core/api/health.py
> +        _LOGGER.error("Could get disk stats due to {}".format(str(ex)))
Error message should read "Could not get disk stats..."

2022-09-16 09:25 UTC, MarkRiddoch approved these changes

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/common/microservice_management_client/microservice_management_client.py
> +                _logger.info(resp.status)
please remove this. and also for update_service_for_acl_change_security

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +from fledge.common.common import _FLEDGE_DATA
import _FLEDGE_ROOT too and then use
 data_dir_path = _FLEDGE_DATA if _FLEDGE_DATA else _FLEDGE_ROOT + '/data'

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +     Return the health of Storage service.
& data directory

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +           Health of Storage service.
& data directory

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +        raise web.HTTPNotFound(reason="Cannot ping the storage service. It does not exist in service registry.")
mind adding body json dumps with err = and keep text in err to avoid repetition

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +        ping_response = await mgt_client.ping_service()
response as you will augment it with disk stuff too

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +        disk_check_process = await asyncio.create_subprocess_shell('df -k ' + _FLEDGE_DATA,
use data_dir_path, not _FLEDGE_DATA (as stated above)

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +        return web.json_response(ping_response)
move to else after except

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +        msg = "Could get disk stats due to {}".format(str(ex))
NOT*

Failed to get disk stats! {}

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +        usage = int(required_stats[4].replace("%", ''))
add comments which exact headers are you using? I assume order is always the same on different distributions.

2022-09-16 11:26 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +        # fill all the files values retrieved
fields* though comment is not required

2022-09-16 11:29 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +        return web.json_response(response)
move to else after except

2022-09-16 12:34 UTC, AmandeepArora approved these changes

2022-09-16 14:27 UTC, praveen-garg approved these changes

2022-09-16 14:27 UTC, praveen-garg commented on python/fledge/services/core/api/health.py
> +        response['disk']['status'] = status
this should have been in try block only, I only meant final response

2022-09-16 14:41 UTC, merged