FOGL-7074 Make storage plugin selection a choice from a drop down list
fledge-iot/fledge pull request #865
Opened 2022-10-28 13:55 UTC by MarkRiddoch

Signed-off-by: Mark Riddoch <mark@dianomic.com>

2022-11-03 11:59 UTC, pintomax approved these changes

2022-11-04 07:16 UTC, ashish-jabble requested changes
Now with fresh instance it's fine.
But with existing/upgrade way it's still come up with old configuration of Storage category.
Detailed testing notes are available on [FOGL-7074 JIRA](https://scaledb.atlassian.net/browse/FOGL-7074?focusedCommentId=47004&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-47004)

2022-11-08 14:24 UTC, pintomax submitted a review, later dismissed

2022-11-28 09:58 UTC, ashish-jabble commented
@MarkRiddoch Now things are good with above commits. But having some concerns related with readingPlugin value is empty in storage.json when upgrade And on fresh setup there are some syslog errors related with No such category found (Storage). Detailed notes are available on [JIRA](https://scaledb.atlassian.net/browse/FOGL-7074?focusedCommentId=47076&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-47076)

2023-01-13 16:37 UTC, pintomax approved these changes

2023-01-17 09:15 UTC, ashish-jabble commented on C/services/storage/storage.cpp
> +		// configuration cache has been manaully reset or altered while Fledge was down
manually

2023-01-17 09:41 UTC, ashish-jabble approved these changes
LGTM!

2023-01-17 09:43 UTC, ashish-jabble commented
@MarkRiddoch on fledge reset we are not resetting `storage.json`. Shall we now?

2023-01-17 09:53 UTC, MarkRiddoch commented
> @MarkRiddoch on fledge reset we are not resetting `storage.json`. Shall we now?

I don't think we should.

2023-01-17 14:25 UTC, pintomax approved these changes

2023-01-17 14:30 UTC, merged